version: '3.8'

services:
  backend:
    build:
      context: ./backend
    networks:
      - backend_net
    depends_on:
      - db
    environment:
      - PORT=80
    env_file:
      - ./app/backend/.env
    ports:
      - "8080:80"
  db:
    image: postgres:alpine
    networks:
      - backend_net
    env_file:
      - ./app/backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  backend_net:
    driver: bridge