version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=slashurl
      - POSTGRES_DOMAIN=db
    networks:
      - backend_net
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=slashurl
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge