version: '3.8'

services:
  backend:
    environment:
      - PORT=80
    env_file:
      - ./.env.prod
  db:
    env_file:
      - ./.env.prod
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: