version: '3.8'

services:
  backend:
    build:
      context: ./backend
    networks:
      - backend_net
    depends_on:
      - db
  db:
    image: postgres:alpine
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge