// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::Queryable;
use serde::Serialize;
#[derive(Queryable, Debug, Serialize)]
pub struct Url {
    pub id: i32,
    pub short_url: String,
    pub full_url: String,
    pub visits: i32,
    pub created_at: NaiveDateTime,
}
